-- Finance core: accounts, categories, contacts, transactions and the khata
-- ledger (contact_transactions).
--
-- Conventions for every syncable table (docs/07_OFFLINE_SYNC.md):
--   * id is generated by the client (UUID v4) so rows can be created offline;
--     retries upsert on id, which makes uploads idempotent.
--   * user_id defaults to auth.uid(); RLS rejects any other value.
--   * deleted_at is a tombstone. Synced rows are soft-deleted so deletes
--     propagate to other devices.
--   * References to a user's own accounts/contacts are composite foreign keys
--     on (user_id, <ref>_id), so a row can never point at another user's data.
--   * Those references use the default NO ACTION delete rule: a row that is
--     still referenced cannot be hard-deleted, protecting financial history.
--     Deleting the auth user cascades through everything in one statement.

-- ---------------------------------------------------------------------------
-- accounts
-- ---------------------------------------------------------------------------
create table public.accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid()
    references auth.users (id) on delete cascade,
  name text not null check (btrim(name) <> ''),
  type text not null check (type in ('cash', 'bank', 'upi', 'card', 'other')),
  -- May be negative: a card or overdrawn bank account can start in debt.
  opening_balance numeric(18, 2) not null default 0,
  opening_balance_date date not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  unique (user_id, id)
);

create trigger set_updated_at
  before insert or update on public.accounts
  for each row execute function private.set_updated_at();

-- ---------------------------------------------------------------------------
-- categories: system categories are shared and ownerless (user_id null);
-- every other category belongs to exactly one user.
-- ---------------------------------------------------------------------------
create table public.categories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid default auth.uid()
    references auth.users (id) on delete cascade,
  name text not null check (btrim(name) <> ''),
  type text not null check (type in ('income', 'expense', 'both')),
  icon text,
  is_system boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint categories_owner_check check (is_system = (user_id is null))
);

create index categories_user_id_idx on public.categories (user_id);

create trigger set_updated_at
  before insert or update on public.categories
  for each row execute function private.set_updated_at();

-- True when the category is a system category or belongs to the caller.
-- Categories can't use a composite foreign key because system rows have no
-- owner, so policies on referencing tables call this instead.
create function private.can_use_category(target_category_id uuid)
returns boolean
language sql
stable
set search_path = ''
as $$
  select target_category_id is null
    or exists (
      select 1
      from public.categories c
      where c.id = target_category_id
        and (c.is_system or c.user_id = (select auth.uid()))
    );
$$;

grant execute on function private.can_use_category(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- contacts (khata parties)
-- ---------------------------------------------------------------------------
create table public.contacts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid()
    references auth.users (id) on delete cascade,
  name text not null check (btrim(name) <> ''),
  mobile text,
  email text,
  address text,
  notes text,
  -- Magnitude only; the direction is opening_balance_type.
  opening_balance numeric(18, 2) not null default 0
    check (opening_balance >= 0),
  opening_balance_type text not null default 'receivable'
    check (opening_balance_type in ('receivable', 'payable')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  unique (user_id, id)
);

create trigger set_updated_at
  before insert or update on public.contacts
  for each row execute function private.set_updated_at();

-- ---------------------------------------------------------------------------
-- transactions
-- ---------------------------------------------------------------------------
create table public.transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid()
    references auth.users (id) on delete cascade,
  account_id uuid not null,
  category_id uuid references public.categories (id),
  contact_id uuid,
  type text not null check (type in (
    'income', 'expense', 'credit', 'debit', 'payment_received',
    'payment_made', 'transfer_in', 'transfer_out', 'opening_balance',
    'adjustment'
  )),
  amount numeric(18, 2) not null check (amount > 0),
  transaction_date timestamptz not null default now(),
  note text,
  description text,
  payment_method text,
  attachment_url text,
  -- Shared by the transfer_out and transfer_in legs of one transfer.
  transfer_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  foreign key (user_id, account_id) references public.accounts (user_id, id),
  foreign key (user_id, contact_id) references public.contacts (user_id, id),
  constraint transactions_transfer_check check (
    (type in ('transfer_in', 'transfer_out')) = (transfer_id is not null)
  )
);

create index transactions_user_date_idx
  on public.transactions (user_id, transaction_date desc);
create index transactions_user_account_date_idx
  on public.transactions (user_id, account_id, transaction_date desc);
-- category_id leads (not user_id) so foreign key checks on category deletes
-- can use this index; (user_id, category_id) lookups are served equally well.
create index transactions_category_user_date_idx
  on public.transactions (category_id, user_id, transaction_date desc);
create index transactions_user_contact_idx
  on public.transactions (user_id, contact_id)
  where contact_id is not null;
-- A transfer is exactly one outgoing and one incoming leg, on two different
-- accounts.
create unique index transactions_transfer_leg_key
  on public.transactions (transfer_id, type)
  where transfer_id is not null;
create unique index transactions_transfer_account_key
  on public.transactions (transfer_id, account_id)
  where transfer_id is not null;

create trigger set_updated_at
  before insert or update on public.transactions
  for each row execute function private.set_updated_at();

-- ---------------------------------------------------------------------------
-- contact_transactions (khata ledger entries)
-- ---------------------------------------------------------------------------
create table public.contact_transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid()
    references auth.users (id) on delete cascade,
  contact_id uuid not null,
  type text not null check (type in (
    'credit', 'debit', 'payment_received', 'payment_made', 'adjustment'
  )),
  amount numeric(18, 2) not null check (amount > 0),
  transaction_date timestamptz not null default now(),
  due_date date,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  foreign key (user_id, contact_id) references public.contacts (user_id, id)
);

create index contact_transactions_user_contact_date_idx
  on public.contact_transactions (user_id, contact_id, transaction_date desc);

create trigger set_updated_at
  before insert or update on public.contact_transactions
  for each row execute function private.set_updated_at();

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------
alter table public.accounts enable row level security;
alter table public.categories enable row level security;
alter table public.contacts enable row level security;
alter table public.transactions enable row level security;
alter table public.contact_transactions enable row level security;

revoke all on table
  public.accounts, public.categories, public.contacts,
  public.transactions, public.contact_transactions
from anon, authenticated;
grant select, insert, update, delete on table
  public.accounts, public.categories, public.contacts,
  public.transactions, public.contact_transactions
to authenticated;

-- accounts
create policy "Users can view their own accounts"
  on public.accounts for select to authenticated
  using (user_id = (select auth.uid()));
create policy "Users can create their own accounts"
  on public.accounts for insert to authenticated
  with check (user_id = (select auth.uid()));
create policy "Users can update their own accounts"
  on public.accounts for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));
create policy "Users can delete their own accounts"
  on public.accounts for delete to authenticated
  using (user_id = (select auth.uid()));

-- categories: system categories are readable by every signed-in user and
-- writable by nobody through the API.
create policy "Users can view system and their own categories"
  on public.categories for select to authenticated
  using (is_system or user_id = (select auth.uid()));
create policy "Users can create their own categories"
  on public.categories for insert to authenticated
  with check (user_id = (select auth.uid()) and not is_system);
create policy "Users can update their own categories"
  on public.categories for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()) and not is_system);
create policy "Users can delete their own categories"
  on public.categories for delete to authenticated
  using (user_id = (select auth.uid()));

-- contacts
create policy "Users can view their own contacts"
  on public.contacts for select to authenticated
  using (user_id = (select auth.uid()));
create policy "Users can create their own contacts"
  on public.contacts for insert to authenticated
  with check (user_id = (select auth.uid()));
create policy "Users can update their own contacts"
  on public.contacts for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));
create policy "Users can delete their own contacts"
  on public.contacts for delete to authenticated
  using (user_id = (select auth.uid()));

-- transactions
create policy "Users can view their own transactions"
  on public.transactions for select to authenticated
  using (user_id = (select auth.uid()));
create policy "Users can create their own transactions"
  on public.transactions for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and private.can_use_category(category_id)
  );
create policy "Users can update their own transactions"
  on public.transactions for update to authenticated
  using (user_id = (select auth.uid()))
  with check (
    user_id = (select auth.uid())
    and private.can_use_category(category_id)
  );
create policy "Users can delete their own transactions"
  on public.transactions for delete to authenticated
  using (user_id = (select auth.uid()));

-- contact_transactions
create policy "Users can view their own contact transactions"
  on public.contact_transactions for select to authenticated
  using (user_id = (select auth.uid()));
create policy "Users can create their own contact transactions"
  on public.contact_transactions for insert to authenticated
  with check (user_id = (select auth.uid()));
create policy "Users can update their own contact transactions"
  on public.contact_transactions for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));
create policy "Users can delete their own contact transactions"
  on public.contact_transactions for delete to authenticated
  using (user_id = (select auth.uid()));
